set nocompatible

" =================================================
" PLUG
" =================================================

call plug#begin('~/.local/share/nvim/plugged')

" if has('nvim')
"  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
" else
"  Plug 'Shougo/deoplete.nvim'
"  Plug 'roxma/nvim-yarp'
"  Plug 'roxma/vim-hug-neovim-rpc'
" endif
" Plug 'fishbullet/deoplete-ruby'
" Plug 'tbodt/deoplete-tabnine', { 'do': './install.sh' }

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Automatically deal with swap file warnings
" Plug 'gioele/vim-autoswap'

" Plug 'mg979/vim-visual-multi'
" Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'christoomey/vim-tmux-navigator'
Plug 'editorconfig/editorconfig-vim'
" Plug 'ervandew/supertab'

Plug 'janko-m/vim-test'
Plug 'jlanzarotta/bufexplorer'
Plug 'ludovicchabant/vim-gutentags'

Plug 'scrooloose/nerdcommenter'

Plug 'skywind3000/asyncrun.vim'
Plug 'w0rp/ale'

" auto close ({[ etc.
Plug 'Townk/vim-autoclose'
" auto close x/html tags
Plug 'alvan/vim-closetag'
Plug 'adelarsq/vim-matchit'


" The Tim Pope collection
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-dispatch'

" Language/templating/framework plugins
Plug 'elixir-editors/vim-elixir'
Plug 'elmcast/elm-vim'
Plug 'mattn/emmet-vim'
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'slim-template/vim-slim'
Plug 'tpope/vim-rails'
Plug 'c-brenn/phoenix.vim'
Plug 'slashmili/alchemist.vim'
Plug 'posva/vim-vue'
Plug 'jimmyhchan/dustjs.vim'

call plug#end()

" =================================================
" END PLUG
" =================================================

syntax on
filetype on
filetype indent on
filetype plugin on

let mapleader = " "
set clipboard=unnamedplus
set backspace=2
set autowrite
set splitright
set title titlestring=
set nojoinspaces " Use one space, not two, after punctuation.
set nu
set rnu
set noerrorbells visualbell t_vb= " no bloody beeping
autocmd GUIEnter * set visualbell t_vb=
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab
set hidden " keeps buffers in memory when not in view, preserves history, marks etc.
set list listchars=tab:»·,trail:·,nbsp:· " Display extra whitespace
setlocal list listchars=tab:»·,trail:·,nbsp:·
set history=50  " Number of things to remember in history.
set timeoutlen=500
set backup                     " Enable creation of backup file.
set backupdir=~/.dotfiles/vim/backups// " Where backups will go.
set directory=~/.dotfiles/vim/tmp//     " Where temporary files will go.
set noswapfile
"set nobackup

" Highlight the 81st column on any line that exceeds 80 columns
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" disable comments automatically continuing on next line if press return
autocmd filetype * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" set .md files to markdown syntax
autocmd BufNewFile,BufRead *.md set filetype=markdown

" ==============================================================
"                    NERDCOMMENTER
" ==============================================================
let g:NERDSpaceDelims = 1 " Add spaces after comment delimiters by default
let g:NERDDefaultAlign = 'left' " Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDTrimTrailingWhitespace = 1 " Enable trimming of trailing whitespace when uncommenting
let g:NERDCustomDelimiters = { 'eruby.yaml': { 'left': '#' }, 'dustjs': { 'left': '{!', 'right': '!}' } }
let g:NERDCommentEmptyLines = 1


" ==============================================================
"                    RIPGREP
" ==============================================================
nnoremap K :Rg <C-R><C-W><CR>
nnoremap \ :Rg<SPACE>


" ==============================================================
"                    ALCHEMIST
" ==============================================================
let g:alchemist_keyword_map = '-'
" let g:alchemist_keyword_map = '<leader>K'
let g:alchemist_tag_disable = 1

" ==============================================================
"                          NETRW
" ==============================================================
" Hide banner, uncomment this once used to commands?
" let g:netrw_banner = 0


" ==============================================================
"                          ALE
" ==============================================================
highlight ALEWarning ctermbg=Black
let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'ruby': ['rubocop'],
\   'javascript': ['eslint'],
\   'css': ['prettier'],
\   'markdown': ['prettier'],
\   'erb': ['erb'],
\   'elixir': ['mix_format'],
\   'elm': ['elm-format']
\}

" phoenix code reloading doesn't work without this
let g:ale_linters = {
\   'elixir': ['mix'],
\   'javascript': ['eslint'],
\   'ruby': ['rubocop']
\}

let g:ale_sign_error = '●' " Less aggressive than the default '>>'
let g:ale_sign_warning = '.'
let g:ale_lint_on_enter = 0 " Less distracting when opening a new file


" ==============================================================
"                          RUBY SPECIFIC SETTINGS
" ==============================================================

" ruby path if you are using rbenv
" let g:ruby_path = system('echo $HOME/.rbenv/shims')

" Auto complete Ruby
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1

let test#strategy = "neovim"
" let test#neovim#term_position = "vertical topleft split"
" let test#ruby#minitest#file_pattern = '_spec\.rb' " the default is '_test\.rb'

let g:rails_projections = {
      \ "app/lib/*.rb": {
      \   "test": [
      \     "test/lib/{}_test.rb",
      \     "spec/lib/{}_spec.rb"
      \   ]
      \ }
      \}

let g:projectionist_heuristics = {
      \ "*": {
      \  "apps/*.rb": { "alternate": "spec/{}_spec.rb", "type": "source" },
      \  "spec/*_spec.rb": { "alternate": "apps/{}.rb", "type": "test" },
      \  "lib/*.ex": {"alternate": "test/{}_test.exs", "type": "source" },
      \  "test/*_test.exs": { "alternate": "lib/{}.ex", "type": "test" }
      \ }
      \}


" ==============================================================
"                          VIM SNIPPETS SETTINGS
" ==============================================================
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsListSnippets="<C-tab>"
let g:UltiSnipsJumpForwardTrigger="<C-a>"
let g:UltiSnipsJumpBackwardTrigger="<C-z>"
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetsDir="~/.vim/UltiSnips/"
let g:UltiSnipsSnippetDirectories=["~/.vim/UltiSnips/", "UltiSnips"]


" ==============================================================
"                     EMMET SETTINGS
" ==============================================================
let g:user_emmet_leader_key='<c-m>'
let g:user_emmet_install_global = 0
autocmd FileType html,css,scss,eruby EmmetInstall
let g:user_emmet_settings = {
  \  'javascript.jsx' : {
  \      'extends' : 'jsx',
  \  },
  \}

" ==============================================================
"                     javascript settings
" ==============================================================
" autocmd bufwritepost *.js asyncrun -post=checktime ./node_modules/.bin/eslint --fix %


" ==============================================================
"                     editorconfig settings
" ==============================================================
let g:editorconfig_exclude_patterns = ['fugitive://.*']


" ==============================================================
"                     elm settings
" ==============================================================
let g:elm_setup_keybindings = 0


" ==============================================================
"                     gutentags settings
" ==============================================================
let g:gutentags_define_advanced_commands = 1
let g:gutentags_exclude_filetypes = ['gitcommit', 'gitrebase', 'conf', 'text', '', 'json']


" =================================================
"                     THEME SETTINGS
" =================================================


colorscheme solarized
let g:airline_powerline_fonts = 1
let g:airline_theme='solarized'

if ($ITERM_PROFILE == 'dark')
 let g:airline_solarized_bg='dark'
 set background=dark
else
 let g:airline_solarized_bg='light'
 set background=light
endif


" =================================================
"                     SUPERTAB SETTINGS
" =================================================
" attempt to determine which completion type to use based on input
let g:SuperTabDefaultCompletionType = "context"


" ==============================================================
"                     LEADER/MAPPINGS
" ==============================================================
" Switch between the last two files
nnoremap <leader><leader> <c-^>
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>

nnoremap <leader>t :w<cr>:TestFile<cr>
nnoremap <leader>s :w<cr>:TestNearest<cr>
nnoremap <leader>a :w<cr>:TestSuite<cr>
nnoremap <leader>l :w<cr>:TestLast<cr>
nnoremap <leader>v :w<cr>:TestVisit<cr>

nnoremap <C-p> :Files<cr>
nnoremap gd <C-]>

" Ruby/Rails leader mappings
nnoremap <leader>rg :e Gemfile<cr>
nnoremap <leader>rr :e config/routes.rb<cr>
nnoremap <leader>rd :e config/database.yml<cr>

" when using nvim map Ctrl-o to come out of insert mode in terminal
if has('nvim')
  tmap <C-o> <C-\><C-n>
endif

" buffer mappings
nnoremap <leader>bd :bd<cr>
nnoremap <leader>bda :%bd<cr>
nnoremap <leader>b :bu<space>
nnoremap <leader>bn :bn<cr>
nnoremap <leader>bp :bp<cr>

" ALE leader mappings
nnoremap <leader>af :ALEFix<cr>
nnoremap <leader>an :ALENext<cr>
nnoremap <leader>ap :ALEPrevious<cr>
nnoremap <leader>ad :ALEDetail<cr>

" Netrw mappings
nnoremap <leader>e :Explore<cr>
nnoremap <leader>er :e.<cr>
nnoremap <leader>ev :Vex<cr>
nnoremap <leader>es :Sex<cr>
nnoremap <leader>evr :vs.<cr>
nnoremap <leader>esr :sp.<cr>

" Fugitive mappings
nnoremap <leader>ga :Git add %:p<cr><cr>
nnoremap <leader>gs :Gstatus<cr>
" nnoremap <leader>gc :Gcommit -v -q<CR>
nnoremap <leader>gc :Dispatch git commit<cr>
" nnoremap <leader>gt :Gcommit -v -q %:p<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>ge :Gedit<cr>
nnoremap <leader>gr :Gread<cr>
nnoremap <leader>gw :Gwrite<cr><cr>
" nnoremap <leader>gl :silent! Glog<CR>:bot copen<CR>
nnoremap <leader>gp :Ggrep<Space>
nnoremap <leader>gm :Gmove<Space>
nnoremap <leader>gb :Git branch<Space>
nnoremap <leader>go :Git checkout<Space>
nnoremap <leader>gps :Dispatch! git push<cr>
nnoremap <leader>gpl :Dispatch! git pull<cr>
nnoremap <leader>gl :Gblame<cr>
nnoremap <leader>grm :Gremove<cr>

" ==============================================================
"                     MACROS
" ==============================================================
" add frozen string literal comment to top of ruby files
let @f = 'ggO# frozen_string_literal: true'
" add binding.pry on line above
let@p = 'Obinding.pry'
